### ISSUE TITLE
使用过程几个问题

### ISSUE THREAD

**Issue by long904** [tianshuang/aliyun-oss-sync#1]
HI，
当第二次上传的时候出现类似以下提示信息，这是 Python 版本问题？目录使用是系统自带 python2.6
「  InsecurePlatformWarning
/usr/lib/python2.6/site-packages/requests-2.13.0-py2.6.egg/requests/packages/urllib3/util/ssl_.py:132: InsecurePlatformWarning: A true SSLContext object is not available.」

另外，如果在日常过程中实现实时增量上传？目前我理解是通过 crontab 方式可以实现增量上传，但这并不是实时。如果想要实现实时，请问有何方法？

谢谢。

**Comment by tianshuang** [comment]
关于第一个问题，可以参考 [SSL InsecurePlatform error when using Requests package](http://stackoverflow.com/questions/29099404/ssl-insecureplatform-error-when-using-requests-package)。

**Comment by tianshuang** [comment]
关于第二个问题，我编写该脚本的初始设计并没有考虑实时同步的情况，仅仅是为了自动化发布自己的博客而编写。如果你希望能实时同步到 OSS，建议将 OSS 使用阿里云官方的 [ossfs](https://github.com/aliyun/ossfs) [ossfs 文档](https://help.aliyun.com/document_detail/32196.html?spm=5176.doc44075.6.1023.yAYzab) 挂载为本地文件系统，然后通过 [Lsyncd -- Live Syncing (Mirror) Daemon](https://github.com/axkibe/lsyncd) 之类的工具同步至阿里云 OSS 挂载的目录。这只是我的一个想法，你可以参考下。
