### ISSUE TITLE
掘金推送文章探讨

### ISSUE THREAD

**Issue by it-noob** [tianshuang/aliyun-oss-sync#2]
作者您好，掘金推送您的博客，看完以后有点疑问，想跟您探讨下，发现博客没有留言或者评论模块儿，掘金我发表评论没有权限。关于《Java 为什么对常量的修改没有生效？》一文中说的，我特意测试了下，不知道你用的那种打包机制，增量打包没有对有引用类重新编译，求指教，因为我在maven下是可以全部编译的，抱歉在此新建issue

**Comment by tianshuang** [comment]
没事，是这样的，我们打包机使用 mvn package 命令进行打包。
根据 maven 官方的[文档](https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html)，可以看到默认生命周期中没有包括 clean。
因为工程由多个模块组成，当时出问题的常量内是在另一个模块中，打包时检查到常量模块发生了变化，所以重新编译了常量类所在的模块，而引用常量类的类所在的模块当时并没有发生变化，所以没有被重新编译。
而你在测试过程中，可能并没有模块的拆分，所以将引用常量类的类也重新编译了，故没有重现该现象。这也是我文章中使用命令行进行测试的原因。
